site_name: CLIMB-BIG-DATA Documentation
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: amber
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - attr_list
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

copyright: |
  &copy; CLIMB-BIG-DATA 2023
nav:
  - "Overview": "index.md"
  - "Getting started":
      - "How to Register": "getting-started/how-to-register.md"
      - "Authentication": "getting-started/authentication.md"
  - "Notebook Servers":
      - notebook-servers/index.md
      - "Introduction": "notebook-servers/introduction.md"
      - "Quick start": "notebook-servers/quick-start.md"
      - "Using the terminal": "notebook-servers/using-the-terminal.md"
      - "Understanding storage": "notebook-servers/understanding-storage.md"
      - "Installing software with Conda": "notebook-servers/installing-software-with-conda.md"
